//Get Lang
export const GET_LANGUAGE_REQUEST = 'GET_LANGUAGE_REQUEST';
export const GET_LANGUAGE_SUCCESS = 'GET_LANGUAGE_SUCCESS';
export const GET_LANGUAGE_FAILURE = 'GET_LANGUAGE_FAILURE';

//varify mobile or Get OTP
export const GET_OTP = 'GET_OTP';
export const GET_OTP_SUCCESS = 'GET_OTP_SUCCESS';
export const GET_OTP_FAILURE = 'GET_OTP_FAILURE';

//Verify OTP
export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

//create user
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

//create chat
export const CREATE_CHAT_GROUP = 'CREATE_CHAT_GROUP';
export const CREATE_CHAT_GROUP_SUCCESS = 'CREATE_CHAT_GROUP_SUCCESS';
export const CREATE_CHAT_GROUP_FAILURE = 'CREATE_CHAT_GROUP_FAILURE';

//get Chatroom
export const GET_CHAT_GROUP = 'GET_CHAT_GROUP';
export const GET_CHAT_GROUP_SUCCESS = 'GET_CHAT_GROUP_SUCCESS';
export const GET_CHAT_GROUP_FAILURE = 'GET_CHAT_GROUP_FAILURE';

//get Home
export const HOME_API = 'HOME_API';
export const HOME_API_SUCCESS = 'HOME_API_SUCCESS';
export const HOME_API_FAILURE = 'HOME_API_FAILURE';

//get My Chatroom
export const GET_MY_CHATROOM = 'GET_MY_CHATROOM';
export const GET_MY_CHATROOM_SUCCESS = 'GET_MY_CHATROOM_SUCCESS';
export const GET_MY_CHATROOM_FAILURE = 'GET_MY_CHATROOM_FAILURE';

//get All Chatroom
export const GET_ALL_CHATROOM = 'GET_ALL_CHATROOM';
export const GET_ALL_CHATROOM_SUCCESS = 'GET_ALL_CHATROOM_SUCCESS';
export const GET_ALL_CHATROOM_FAILURE = 'GET_ALL_CHATROOM_FAILURE';

//get All Chatroom
export const JOIN_CHATROOM = 'JOIN_CHATROOM';
export const JOIN_CHATROOM_SUCCESS = 'JOIN_CHATROOM_SUCCESS';
export const JOIN_CHATROOM_FAILURE = 'JOIN_CHATROOM_FAILURE';

//get All MESSAGE
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';

//get All TAGS
export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';

//join Room
export const JOIN_ROOM = 'JOIN_ROOM';
export const JOIN_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const JOIN_ROOM_FAILURE = 'GET_ROOM_FAILURE';

//Audio Request
export const AUDIO_REQUEST = 'AUDIO_REQUEST';
export const AUDIO_REQUEST_SUCCESS = 'AUDIO_REQUEST_SUCCESS';
export const AUDIO_REQUEST_FAILURE = 'AUDIO_REQUEST_FAILURE';

//Accept Reject Request
export const ACCEPT_REJECT_REQUEST = 'ACCEPT_REJECT_REQUEST';
export const ACCEPT_REJECT_REQUEST_SUCCESS = 'ACCEPT_REJECT_REQUEST_SUCCESS';
export const ACCEPT_REJECT_REQUEST_FAILURE = 'ACCEPT_REJECT_REQUEST_FAILURE';

//Get my Chatroom data
export const GET_MY_CHATROOM_DATA = 'GET_MY_CHATROOM_DATA';
export const GET_MY_CHATROOM_DATA_SUCCESS = 'GET_MY_CHATROOM_DATA_SUCCESS';
export const GET_MY_CHATROOM_DATA_FAILURE = 'GET_MY_CHATROOM_DATA_FAILURE';

//Get User Chatroom data
export const GET_USER_CHATROOM_DATA = 'GET_USER_CHATROOM_DATA';
export const GET_USER_CHATROOM_DATA_SUCCESS = 'GET_USER_CHATROOM_DATA_SUCCESS';
export const GET_USER_CHATROOM_DATA_FAILURE = 'GET_USER_CHATROOM_DATA_FAILURE';

//SEND_AUDIO_REQUEST
export const SEND_AUDIO_REQUEST = 'SEND_AUDIO_REQUEST';
export const SEND_AUDIO_REQUEST_SUCCESS = 'SEND_AUDIO_REQUEST_SUCCESS';
export const SEND_AUDIO_REQUEST_FAILURE = 'SEND_AUDIO_REQUEST_FAILURE';

//SEND_WAR_REQUEST
export const SEND_WAR_REQUEST = 'SEND_WAR_REQUEST';
export const SEND_WAR_REQUEST_SUCCESS = 'SEND_WAR_REQUEST_SUCCESS';
export const SEND_WAR_REQUEST_FAILURE = 'SEND_WAR_REQUEST_FAILURE';

//SEND_CP_REQUEST
export const SEND_CP_REQUEST = 'SEND_CP_REQUEST';
export const SEND_CP_REQUEST_SUCCESS = 'SEND_CP_REQUEST_SUCCESS';
export const SEND_CP_REQUEST_FAILURE = 'SEND_CP_REQUEST_FAILURE';

//JOIN_FRANCHISE_REQUEST
export const JOIN_FRANCHISE_REQUEST = 'JOIN_FRANCHISE_REQUEST';
export const JOIN_FRANCHISE_REQUEST_SUCCESS = 'JOIN_FRANCHISE_REQUEST_SUCCESS';
export const JOIN_FRANCHISE_REQUEST_FAILURE = 'JOIN_FRANCHISE_REQUEST_FAILURE';

//FOLLOW_USER_REQUEST
export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_REQUEST_SUCCESS = 'FOLLOW_USER_REQUEST_SUCCESS';
export const FOLLOW_USER_REQUEST_FAILURE = 'FOLLOW_USER_REQUEST_FAILURE';

//UNFOLLOW_USER_REQUEST
export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_REQUEST_SUCCESS = 'UNFOLLOW_USER_REQUEST_SUCCESS';
export const UNFOLLOW_USER_REQUEST_FAILURE = 'UNFOLLOW_USER_REQUEST_FAILURE';

//GET_FRANCHISE
export const GET_FRANCHISE = 'GET_FRANCHISE';
export const GET_FRANCHISE_SUCCESS = 'GET_FRANCHISE_SUCCESS';
export const GET_FRANCHISE_FAILURE = 'GET_FRANCHISE_FAILURE';

//GET_GIFT
export const GET_GIFT = 'GET_GIFT';
export const GET_GIFT_SUCCESS = 'GET_GIFT_SUCCESS';
export const GET_GIFT_FAILURE = 'GET_GIFT_FAILURE';

//GET_STICKER
export const GET_STICKER = 'GET_STICKER';
export const GET_STICKER_SUCCESS = 'GET_STICKER_SUCCESS';
export const GET_STICKER_FAILURE = 'GET_STICKER_FAILURE';

//ADD_MONEY
export const ADD_MONEY = 'ADD_MONEY';
export const ADD_MONEY_SUCCESS = 'ADD_MONEY_SUCCESS';
export const ADD_MONEY_FAILURE = 'ADD_MONEY_FAILURE';

//SENT_ONE_TO_ONE_CHAT_REQUEST
export const SENT_ONE_TO_ONE_CHAT_REQUEST = 'SENT_ONE_TO_ONE_CHAT_REQUEST';
export const SENT_ONE_TO_ONE_CHAT_REQUEST_SUCCESS =
  'SENT_ONE_TO_ONE_CHAT_REQUEST_SUCCESS';
export const SENT_ONE_TO_ONE_CHAT_REQUEST_FAILURE =
  'SENT_ONE_TO_ONE_CHAT_REQUEST_FAILURE';

//GET_ONE_TO_ONE_CHAT_LIST
export const GET_ONE_TO_ONE_CHAT_LIST = 'GET_ONE_TO_ONE_CHAT_LIST';
export const GET_ONE_TO_ONE_CHAT_LIST_SUCCESS =
  'GET_ONE_TO_ONE_CHAT_LIST_SUCCESS';
export const GET_ONE_TO_ONE_CHAT_LIST_FAILURE =
  'GET_ONE_TO_ONE_CHAT_LIST_FAILURE';

//GET_ONE_TO_ONE_CHAT_DETAIL
export const GET_ONE_TO_ONE_CHAT_DETAIL = 'GET_ONE_TO_ONE_CHAT_DETAIL';
export const GET_ONE_TO_ONE_CHAT_DETAIL_SUCCESS =
  'GET_ONE_TO_ONE_CHAT_DETAIL_SUCCESS';
export const GET_ONE_TO_ONE_CHAT_DETAIL_FAILURE =
  'GET_ONE_TO_ONE_CHAT_DETAIL_FAILURE';

//ACCEPT_REJECT_CHAT_REQUEST
export const ACCEPT_REJECT_CHAT_REQUEST = 'ACCEPT_REJECT_CHAT_REQUEST';
export const ACCEPT_REJECT_CHAT_REQUEST_SUCCESS =
  'ACCEPT_REJECT_CHAT_REQUEST_SUCCESS';
export const ACCEPT_REJECT_CHAT_REQUEST_FAILURE =
  'ACCEPT_REJECT_CHAT_REQUEST_FAILURE';

//PENDING_LIST
export const PENDING_LIST = 'PENDING_LIST';
export const PENDING_LIST_SUCCESS = 'PENDING_LIST_SUCCESS';
export const PENDING_LIST_FAILURE = 'PENDING_LIST_FAILURE';

//GET_WALLET
export const GET_WALLET = 'GET_WALLET';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAILURE = 'GET_WALLET_FAILURE';

//GET_USER_DETAIL
export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILURE = 'GET_USER_DETAIL_FAILURE';

//UPLOAD_IMAGE
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';
//UPDATE_PROFILE
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//DELETE_CHATROOM
export const DELETE_CHATROOM = 'DELETE_CHATROOM';
export const DELETE_CHATROOM_SUCCESS = 'DELETE_CHATROOM_SUCCESS';
export const DELETE_CHATROOM_FAILURE = 'DELETE_CHATROOM_FAILURE';

//REMOVE_FROM_AUDIO_CHATROOM
export const REMOVE_FROM_AUDIO_CHATROOM = 'REMOVE_FROM_AUDIO_CHATROOM';
export const REMOVE_FROM_AUDIO_CHATROOM_SUCCESS =
  'REMOVE_FROM_AUDIO_CHATROOM_SUCCESS';
export const REMOVE_FROM_AUDIO_CHATROOM_FAILURE =
  'REMOVE_FROM_AUDIO_CHATROOM_FAILURE';

//FRANCHISE_DETAIL
export const FRANCHISE_DETAIL = 'FRANCHISE_DETAIL';
export const FRANCHISE_DETAIL_SUCCESS = 'FRANCHISE_DETAIL_SUCCESS';
export const FRANCHISE_DETAIL_FAILURE = 'FRANCHISE_DETAIL_FAILURE';

//GET_FRANCHISE_REQUEST
export const GET_FRANCHISE_REQUEST = 'GET_FRANCHISE_REQUEST';
export const GET_FRANCHISE_REQUEST_SUCCESS = 'GET_FRANCHISE_REQUEST_SUCCESS';
export const GET_FRANCHISE_REQUEST_FAILURE = 'GET_FRANCHISE_REQUEST_FAILURE';

//LEADER_BOARD_GIFTER
export const LEADER_BOARD_GIFTER = 'LEADER_BOARD_GIFTER';
export const LEADER_BOARD_GIFTER_SUCCESS = 'LEADER_BOARD_GIFTER_SUCCESS';
export const LEADER_BOARD_GIFTER_FAILURE = 'LEADER_BOARD_GIFTER_FAILURE';

//ACCEPT_REJECT_FRANCHISE_REQUEST
export const ACCEPT_REJECT_FRANCHISE_REQUEST =
  'ACCEPT_REJECT_FRANCHISE_REQUEST';
export const ACCEPT_REJECT_FRANCHISE_REQUEST_SUCCESS =
  'GET_FRANCHISE_REQUEST_SUCCESS';
export const ACCEPT_REJECT_FRANCHISE_REQUEST_FAILURE =
  'GET_FRANCHISE_REQUEST_FAILURE';

// CREATE_ORDER
export const CREATE_ORDER = 'CREATE_ORDER';
// REMOVE_USER_FROM_FRANCHISE
export const REMOVE_USER_FROM_FRANCHISE = 'REMOVE_USER_FROM_FRANCHISE';
// SAVE_TRANSACTION
export const SAVE_TRANSACTION = 'SAVE_TRANSACTION';

//GET_MY_LEVEL
export const GET_MY_LEVEL = 'GET_MY_LEVEL';

//GET_SUPPORTER
export const GET_SUPPORTER = 'GET_SUPPORTER';
//GET_GROUP_MESSAGE
export const GET_GROUP_MESSAGE = 'GET_GROUP_MESSAGE';

//GET_ALL_CHAT_ROOM
export const GET_ALL_CHAT_ROOM = 'GET_ALL_CHAT_ROOM';

//LOGOUT
export const LOGOUT = 'LOGOUT';

//SEARCH
export const SEARCH = 'SEARCH';

//GET_MY_PROFILE
export const GET_MY_PROFILE = 'GET_MY_PROFILE';

//HELP
export const HELP = 'HELP';

//GET_ALL_TRENDING_CHATROOM
export const GET_ALL_TRENDING_CHATROOM = 'GET_ALL_TRENDING_CHATROOM';

//GET_ALL_TOP_CHATROOM
export const GET_ALL_TOP_CHATROOM = 'GET_ALL_TOP_CHATROOM';

//GET_COIN
export const GET_COIN = 'GET_COIN';

//GET_FRAME
export const GET_FRAME = 'GET_FRAME';

//BUY_FRAME
export const BUY_FRAME = 'BUY_FRAME';

//ACTIVE_FRAME
export const ACTIVE_FRAME = 'ACTIVE_FRAME';

//GET_BACKGROUND_IMAGE
export const GET_BACKGROUND_IMAGE = 'GET_BACKGROUND_IMAGE';

//BUY_BACKGROUND_IMAGE
export const BUY_BACKGROUND_IMAGE = 'BUY_BACKGROUND_IMAGE';

//ACTIVE_BACKGROUND_IMAGE
export const ACTIVE_BACKGROUND_IMAGE = 'ACTIVE_BACKGROUND_IMAGE';

//GET_ENTRY
export const GET_ENTRY = 'GET_ENTRY';

//BUY_ENTRY
export const BUY_ENTRY = 'BUY_ENTRY';

//ACTIVE_ENTRY
export const ACTIVE_ENTRY = 'ACTIVE_ENTRY';
