export const getImage = image => {
  switch (image) {
    case 'background':
      return require('../assets/images/syizu_background.png');
    case 'my_splash':
      return require('../assets/images/my_splash.png');
    case 'flag':
      return require('../assets/images/in_flag.png');
    case 'banner':
      return require('../assets/images/banner.png');
    case 'groupImage':
      return require('../assets/images/groupimage.png');
    case 'activechat':
      return require('../assets/images/activechat.png');
    case 'rightArrow':
      return require('../assets/images/rightArrow.png');
    case 'itemBack':
      return require('../assets/images/itemBackground.png');
    case 'adsImage':
      return require('../assets/images/adsimage.png');
    case 'messageImage':
      return require('../assets/images/message_image.png');
    case 'publicImage':
      return require('../assets/images/public_image.png');
    case 'privateImage':
      return require('../assets/images/privateImage.png');
    case 'primaryGrad':
      return require('../assets/images/primaryGrad.png');
    case 'topCpBack':
      return require('../assets/images/winner_board.png');
    case 'coin':
      return require('../assets/images/coin.png');
    case 'homeRel':
      return require('../assets/images/home_relation.png');
    case 'topGifterBack':
      return require('../assets/images/topGifterBack.png');
    case 'profileCover':
      return require('../assets/images/profileCover.png');
    case 'levelImage':
      return require('../assets/images/levelImage.png');
    case 'walletTopBack':
      return require('../assets/images/walletTopBack2.png');
    case 'coinBack':
      return require('../assets/images/coinBack.png');
    case 'vipOffers':
      return require('../assets/images/vipoffers.png');
    case 'chatroomBack':
      return require('../assets/images/chatroomBack.png');
    case 'demoImage':
      return require('../assets/images/demoImage.png');
    case 'RefreshChat':
      return require('../assets/images/RefreshChat.png');
    case 'privacyBack':
      return require('../assets/images/privacyBack.png');
    case 'calender':
      return require('../assets/images/calendar.png');
    case 'bell':
      return require('../assets/images/belll.png');
    case 'refresh':
      return require('../assets/images/refresh.png');
    case 'battleBack':
      return require('../assets/images/battle_back.png');
    case 'warRoomBack':
      return require('../assets/images/war_room_pop_back.png');
    case 'cpBack':
      return require('../assets/images/cpback.png');
    case 'messageIcon':
      return require('../assets/images/messageIcon.png');
    case 'breakupBack':
      return require('../assets/images/breakupBack.png');
    case 'loveRel':
      return require('../assets/images/loveRel.png');
    case 'winnerBack':
      return require('../assets/images/winnerBack.png');
    case 'winnerIcon':
      return require('../assets/images/winnerIcon.png');
    case 'winnerUser':
      return require('../assets/images/winnerUser.png');
    case 'messageBack':
      return require('../assets/images/messageBack.png');
    case 'bestieRel':
      return require('../assets/images/bestieRel.png');
    case 'close':
      return require('../assets/images/close.png');
    case 'frame':
      return require('../assets/images/daisy.png');
    case 'f2':
      return require('../assets/images/f2.png');
    case 'topReceiver':
      return require('../assets/images/topReceiver.jpeg');
    case 'topChat':
      return require('../assets/images/topChat.jpeg');
    case 'topDP':
      return require('../assets/images/topDP.jpeg');
    case 'topGifter':
      return require('../assets/images/topGifter.jpeg');
    case 'top_one_chat':
      return require('../assets/images/top_one_chat.png');
    case 'top_two_chat':
      return require('../assets/images/top_two_chat.png');
    case 'top_three_chat':
      return require('../assets/images/top_three_chat.png');

    case 'top_gift_one':
      return require('../assets/images/top_gift_one.png');
    case 'top_gift_two':
      return require('../assets/images/top_gift_two.png');
    case 'top_gift_three':
      return require('../assets/images/top_gift_three.png');
    case 'badge_1':
      return require('../assets/images/badge_2.png');
    case 'badge_2':
      return require('../assets/images/badge_1.png');
    case 'badge_3':
      return require('../assets/images/badge_3.png');
    case 'badge_4':
      return require('../assets/images/badge_4.png');
    case 'badge_5':
      return require('../assets/images/badge_6.png');
    case 'badge_6':
      return require('../assets/images/badge_5.png');
    case 'badge_7':
      return require('../assets/images/badge_7.png');
    case 'top_chatroom':
      return require('../assets/images/top_chatroom.jpg');
    case 'top_agency':
      return require('../assets/images/top_agency.jpg');
    case 'top_cp':
      return require('../assets/images/top_cp.jpg');
    case 'top_gifter_leaderboard':
      return require('../assets/images/top_gifter_leaderboard.jpg');
    case 'top_received':
      return require('../assets/images/top_received.jpg');
  }
};
